name: p1-mini-c4
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - requests=2.32.5
  - tqdm=4.67.1
  - pip:
      - warcio==1.8.1
      - trafilatura==2.0.0
      - ray==2.54.1
      - datasketch==1.9.0
      - fasttext-wheel==0.9.2
      - kenlm==0.3.0
